<template>
  <svg
    width="280"
    height="180"
    viewBox="0 0 280 180"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      width="280"
      height="180"
      fill="var(--el-fill-color-light)"
    />
    <g filter="url(#filter0_d_search)">
      <rect
        x="60"
        y="54"
        width="160"
        height="72"
        rx="2"
        fill="var(--el-fill-color-blank)"
      />
      <rect
        x="59.7"
        y="53.7"
        width="160.6"
        height="72.6"
        rx="2.3"
        stroke="var(--el-border-color-dark)"
        stroke-width="0.6"
      />
    </g>
    <circle
      cx="100"
      cy="90"
      r="15"
      stroke="var(--el-color-primary)"
      stroke-width="2"
    />
    <path
      d="M110 100L120 110"
      stroke="var(--el-color-primary)"
      stroke-width="2"
      stroke-linecap="round"
    />
    <rect
      x="140"
      cy="85"
      width="60"
      height="10"
      rx="1"
      fill="var(--el-border-color-light)"
    />
  </svg>
</template>
