/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IRiCodeLine: typeof import('~icons/ri/code-line')['default']
    IRiFileCopyLine: typeof import('~icons/ri/file-copy-line')['default']
    IRiGithubLine: typeof import('~icons/ri/github-line')['default']
    OvButton: typeof import('./.vitepress/vitepress/components/overview-icons/ov-button.vue')['default']
    OvConfigProvider: typeof import('./.vitepress/vitepress/components/overview-icons/ov-config-provider.vue')['default']
    OvDatePicker: typeof import('./.vitepress/vitepress/components/overview-icons/ov-date-picker.vue')['default']
    OvDialog: typeof import('./.vitepress/vitepress/components/overview-icons/ov-dialog.vue')['default']
    Overview: typeof import('./.vitepress/vitepress/components/overview.vue')['default']
    OvForm: typeof import('./.vitepress/vitepress/components/overview-icons/ov-form.vue')['default']
    OvInput: typeof import('./.vitepress/vitepress/components/overview-icons/ov-input.vue')['default']
    OvMotion: typeof import('./.vitepress/vitepress/components/overview-icons/ov-motion.vue')['default']
    OvSearch: typeof import('./.vitepress/vitepress/components/overview-icons/ov-search.vue')['default']
    OvSelect: typeof import('./.vitepress/vitepress/components/overview-icons/ov-select.vue')['default']
    OvStatus: typeof import('./.vitepress/vitepress/components/overview-icons/ov-status.vue')['default']
    OvTable: typeof import('./.vitepress/vitepress/components/overview-icons/ov-table.vue')['default']
    OvUpload: typeof import('./.vitepress/vitepress/components/overview-icons/ov-upload.vue')['default']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpCatalog: typeof import('./.vitepress/vitepress/components/vp-catalog.vue')['default']
    VpChangelog: typeof import('./.vitepress/vitepress/components/vp-changelog.vue')['default']
    VpContent: typeof import('./.vitepress/vitepress/components/vp-content.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpMarkdown: typeof import('./.vitepress/vitepress/components/vp-markdown.vue')['default']
    VpSidebar: typeof import('./.vitepress/vitepress/components/vp-sidebar.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/vp-source-code.vue')['default']
  }
}

// For TSX support
declare global {
  const IRiCodeLine: typeof import('~icons/ri/code-line')['default']
  const IRiFileCopyLine: typeof import('~icons/ri/file-copy-line')['default']
  const IRiGithubLine: typeof import('~icons/ri/github-line')['default']
  const OvButton: typeof import('./.vitepress/vitepress/components/overview-icons/ov-button.vue')['default']
  const OvConfigProvider: typeof import('./.vitepress/vitepress/components/overview-icons/ov-config-provider.vue')['default']
  const OvDatePicker: typeof import('./.vitepress/vitepress/components/overview-icons/ov-date-picker.vue')['default']
  const OvDialog: typeof import('./.vitepress/vitepress/components/overview-icons/ov-dialog.vue')['default']
  const Overview: typeof import('./.vitepress/vitepress/components/overview.vue')['default']
  const OvForm: typeof import('./.vitepress/vitepress/components/overview-icons/ov-form.vue')['default']
  const OvInput: typeof import('./.vitepress/vitepress/components/overview-icons/ov-input.vue')['default']
  const OvMotion: typeof import('./.vitepress/vitepress/components/overview-icons/ov-motion.vue')['default']
  const OvSearch: typeof import('./.vitepress/vitepress/components/overview-icons/ov-search.vue')['default']
  const OvSelect: typeof import('./.vitepress/vitepress/components/overview-icons/ov-select.vue')['default']
  const OvStatus: typeof import('./.vitepress/vitepress/components/overview-icons/ov-status.vue')['default']
  const OvTable: typeof import('./.vitepress/vitepress/components/overview-icons/ov-table.vue')['default']
  const OvUpload: typeof import('./.vitepress/vitepress/components/overview-icons/ov-upload.vue')['default']
  const VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
  const VpCatalog: typeof import('./.vitepress/vitepress/components/vp-catalog.vue')['default']
  const VpChangelog: typeof import('./.vitepress/vitepress/components/vp-changelog.vue')['default']
  const VpContent: typeof import('./.vitepress/vitepress/components/vp-content.vue')['default']
  const VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
  const VpMarkdown: typeof import('./.vitepress/vitepress/components/vp-markdown.vue')['default']
  const VpSidebar: typeof import('./.vitepress/vitepress/components/vp-sidebar.vue')['default']
  const VpSourceCode: typeof import('./.vitepress/vitepress/components/vp-source-code.vue')['default']
}