/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    OvButton: typeof import('./.vitepress/vitepress/components/overview-icons/ov-button.vue')['default']
    Overview: typeof import('./.vitepress/vitepress/components/overview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpCatalog: typeof import('./.vitepress/vitepress/components/vp-catalog.vue')['default']
    VpChangelog: typeof import('./.vitepress/vitepress/components/vp-changelog.vue')['default']
    VpContent: typeof import('./.vitepress/vitepress/components/vp-content.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpMarkdown: typeof import('./.vitepress/vitepress/components/vp-markdown.vue')['default']
    VpSidebar: typeof import('./.vitepress/vitepress/components/vp-sidebar.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/vp-source-code.vue')['default']
  }
}
